Add Model type to Cadl.Reflection
microsoft/cadl pull request #1524
Opened 2023-01-11 09:18 UTC by pshao25

We have such decorator to be added:
```
extern dec exclude(target: Model);
```
However, `Model` is not in the Cadl.Reflection

2023-01-11 18:07 UTC, allenjzhang commented
@bterlson, @timotheeguerin, @nguerrera, I had an earlier proposal like this, but Tim disagreed and mentioned that object implies model. I don't know if this is a TS convention, but I feel having `model` is clearer.

BTW, if this change is approved, we need to do a pass on existing libraries to update the decorators.

2023-01-11 19:26 UTC, nguerrera commented
I recommend closing this and opening a design issue.

2023-01-13 00:01 UTC, nguerrera requested changes
See above

2023-01-13 05:26 UTC, pshao25 commented
Thanks all. I create issue at https://github.com/microsoft/cadl/issues/1536. And close this PR.

2023-01-13 05:26 UTC, closed without merging