fix cli options
microsoft/cadl pull request #86
Opened 2021-11-30 03:29 UTC by jianyexi

2021-11-30 19:55 UTC, markcowl requested changes

2021-11-30 19:55 UTC, markcowl commented on packages/compiler/core/cli.ts
> +  const serviceCodePath = args["service-code-path"]
similarly, I think all of this code preparing the directory needs to be in the generator itself

2021-11-30 19:55 UTC, markcowl commented on packages/compiler/core/cli.ts
> +          .option("service-code-path", {
Agreed.  does this show  up as ```program.compilerOptions.miscOptions.serviceCodePath```?

2021-12-01 01:53 UTC, jianyexi commented on packages/compiler/core/cli.ts
> +          .option("service-code-path", {
So we need to remove program.compilerOptions.serviceCodePath,  as I used to consider it's a common option for all the service codes in the future

2021-12-01 19:44 UTC, markcowl commented on packages/compiler/core/cli.ts
> +          .option("service-code-path", {
Yes. the extensibility model for cadl models things this way, so we should use this facility - we may have special case clis in the future when we refactor emitters, and these may have different command line options, bot for now, using the emitter-defined extensible options is the right thing.

2021-12-01 19:45 UTC, markcowl commented
Closing this PR, as I think all the necessary changes are in the emitter.

2021-12-01 19:45 UTC, closed without merging